---
language: c

sudo: required

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt update
  - sudo apt install -y ansible

script:
  - cd tests
  - docker-compose up -d
  - ansible-galaxy install -r requirements.yml -p external-roles
  - ansible-playbook site.yml
