---
- name: Set up authorized_keys for the administrator user
  remote_user: administrator
  become: yes
  become_method: sudo
  authorized_key: user=administrator key="{{ item }}" state=present exclusive=yes
  with_file:
    - keys/administrators

- name: Set up authorized_keys for the deploy user
  remote_user: administrator
  become: yes
  become_method: sudo
  authorized_key: user={{ deploy_username }} key="{{ item }}" state=present exclusive=yes
  with_file:
    - keys/deploy_users
  when: deploy_username is defined

- name: Set up authorized_keys for ci on deploy user
  remote_user: administrator
  become: yes
  become_method: sudo
  authorized_key: user={{ deploy_username }} key="{{ item }}" state=present
  with_file:
    - keys/ci-{{ app_environment }}
  when: deploy_username is defined
