- name: Add FPCO Deb Key
  apt_key: url=https://s3.amazonaws.com/download.fpcomplete.com/debian/fpco.key state=present
  when: ansible_distribution == "Debian"

- name: Add FPCO Deb Key
  apt_key: url=https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key state=present
  when: ansible_distribution_release == "Ubuntu"

- name: Add FPCO Deb repository
  apt_repository: repo='deb http://download.fpcomplete.com/debian/jessie stable main' state=present
  when: ansible_distribution_release == "jessie"

- name: Add FPCO Deb repository
  apt_repository: repo='deb http://download.fpcomplete.com/ubuntu trusty main' state=present
  when: ansible_distribution_release == "trusty"

- name: Update packges
  apt: update_cache=yes

- name: Install Stack packges
  apt: name=stack state=present
