---
- include: prebootstrap-tasks.yml
  become: yes
  become_method: sudo
  when: platform == metal
  tags:
    - prebootstrap

- include: aws-prebootstrap-tasks.yml
  become: yes
  become_method: sudo
  when: platform == aws
  tags:
    - prebootstrap


- include: aws-prebootstrap-tasks.yml
  become: yes
  become_method: sudo
  when: platform == rackspace
  tags:
    - prebootstrap

- include: bootstrap-tasks.yml
  become: yes
  become_method: sudo
  tags:
    - bootstrap

- name: Set up application deploy directory
  remote_user: administrator
  become: yes
  become_method: sudo
  file:
    path=/var/projects state=directory
    owner="{{ user_owner_app_directory }}" group="{{ user_group_app_directory }}" mode=0775
  tags:
    - bootstrap
    - create-app-directory
  when: deploy_username is defined

- include: haskell-stack-tasks.yml
  remote_user: administrator
  become: yes
  become_method: sudo
  tags:
    - haskell-stack



