---
- include: prebootstrap-tasks.yml
  remote_user: root
  when: prebootstrap is defined

- include: bootstrap-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  when: bootstrap is defined

- include: haskell-dependencies-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  when: install_haskell_dependencies is defined

- include: haskell-stack-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  when: install_haskell_stack is defined

- include: ruby-dependencies-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  when: install_ruby_dependencies is defined
  tags:
    - ruby-dependencies

- include: set-authorized-keys.yml
  remote_user: "{{ admin_user }}"
  become: yes
  when: add_remove_keys is defined
  tags:
    - add-remove-keys
