---
- include: prebootstrap-tasks.yml
  remote_user: root
  when: prebootstrap is defined

- include: bootstrap-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  when: bootstrap is defined

- include: haskell-dependencies-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  when: install_haskell_dependencies is defined

- include: haskell-stack-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  when: install_haskell_stack is defined

- include: ruby-dependencies-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  when: install_ruby_dependencies is defined

- include: extra-tasks.yml
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  when: add_remove_keys is defined
