---
- include: prebootstrap-tasks.yml
  remote_user: root
  when: prebootstrap is defined

- include: bootstrap-tasks.yml
  remote_user: administrator
  become: yes
  become_method: sudo
  when: bootstrap is defined

- name: Install common Haskell build dependencies
  remote_user: administrator
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present
  when: install_haskell_dependencies is defined
  with_items:
    - libpcre3-dev
    - libsqlite3-dev
    - libpq-dev

- include: haskell-stack-tasks.yml
  remote_user: administrator
  become: yes
  become_method: sudo
  when: install_haskell_stack is defined

- include: ruby-dependencies-tasks.yml
  remote_user: administrator
  become: yes
  become_method: sudo
  when: install_ruby_dependencies is defined

- include: extra-tasks.yml
  remote_user: administrator
  become: yes
  become_method: sudo
  when: add_remove_keys is defined
