---
- name: Set up authorized_keys file for the admin user
  authorized_key:
    user: "{{ sb_debian_base_admin_user }}"
    key: "{{ sb_debian_base_admin_user_authorized_keys | join('\n') }}"
    exclusive: yes
