---
- name: Set up authorized_keys file for the deploy user
  authorized_key:
    user: "{{ sb_debian_base_deploy_user }}"
    key: "{{ sb_debian_base_deploy_user_authorized_keys | join('\n') }}"
    exclusive: yes
