dependencies:
  - role: jnv.unattended-upgrades
    become: yes
    become_method: sudo
    remote_method: administrator
    unattended_origins_patterns:
      - 'origin=Debian,archive=${distro_codename},label=Debian-Security'
    tags:
      - bootstrap

  - role: nickjj.fail2ban
    become: yes
    become_method: sudo
    remote_method: administrator
    tags:
      - bootstrap

  - role: geerlingguy.ntp
    become: yes
    become_method: sudo
    remote_method: administrator
    ntp_timezone: UTC
    tags:
      - bootstrap
