dependencies:
  - role: jnv.unattended-upgrades
    become: yes
    become_method: sudo
    remote_method: administrator
    unattended_origins_patterns:
      - 'origin=Debian,archive=${distro_codename},label=Debian-Security'
    tags:
      - bootstrap

  - role: nickjj.fail2ban
    become: yes
    become_method: sudo
    remote_method: administrator
    tags:
      - bootstrap

  - role: geerlingguy.ntp
    become: yes
    become_method: sudo
    remote_method: administrator
    ntp_timezone: UTC
    tags:
      - bootstrap

  - role: egidijus.nginx-ssl
    become: yes
    become_method: sudo
    remote_method: administrator
    tags:
      - nginx

  - role: ANXS.postgresql
    postgresql_version: 9.3
    postgresql_encoding: 'UTF-8'
    postgresql_locale: 'en_US.UTF-8'

    postgresql_admin_user: "postgres"
    postgresql_default_auth_method: "trust"

    postgresql_cluster_name: "main"
    postgresql_cluster_reset: false
    tags:
      - basic-postgres
