---
- name: Set up application deploy directory
  remote_user: administrator
  become: yes
  become_method: sudo
  file: path=/var/projects state=directory owner=stackbuilders group=stackbuilders mode=0775
  tags:
    - create-app-directory
