---
- name: Set up application deploy directory
  remote_user: "{{ os_username }}"
  become: yes
  become_method: sudo
  file: path=/var/projects state=directory owner="{{ user_owner_app_directory }}" group="{{ user_group_app_directory }}" mode=0775
  tags:
    - create-app-directory
