---
- name: Install common Haskell build dependencies
  remote_user: "{{ os_username }}"
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present
  with_items:
    - libpcre3-dev
    - libsqlite3-dev
    - libpq-dev
  tags:
    - haskell-build-dependencies
