---
- name: Install ruby dependencies
  remote_user: "{{ os_username }}"
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present
  with_items:
    - curl
    - git
  tags:
    - bootstrap
    - git
